--- mock environment (production settings)
auto_build: 'compute storage'
infra_fullname: 'Infrastructure Team'
infra_account: 'infra'
infra_password: '\$overrides'
infra_sudoers: 'nopasswd'
cloud_domain: 'mock'
cloud_network: '\$local'
cloud_netmask: '\$local'
cloud_gateway: '\$local'
cloud_dns: '\$local'
use_dhcp: 'yes'
ceph_available: 'no'
acng_host: '\$local \$vm'
acng_port: '3142 13143'
approx_host: '\$local \$vm'
approx_port: '9999 10001'
configs_host: '\$vm'
configs_port: '11888'
ntp_host: '\$local \$vm'
cdn_host: '\$local \$vm'
images_host: '\$vm'
ansible_host: '\$vm'
jump_host: '\$vm'
jenkins_host: '\$vm'
keys_host: '\$vm'
keys_port: '\$vm'
