--- mock environment (production settings)
auto_build: 'compute storage'
infra_fullname: 'Infrastructure Team'
infra_account: 'infra'
infra_password: ''
infra_sudoers: 'nopasswd'
cloud_domain: 'mock'
cloud_network: '$local'
cloud_netmask: '$local'
cloud_gateway: '$local'
cloud_dns: '$local'
use_dhcp: 'yes'
ceph_available: 'no'
acng_host: '$vm'
acng_port: '3142'
approx_host: '$vm'
approx_port: '9999'
http_host: '$vm'
http_port: '80'
http_host: '$vm'
http_port: '80'
ntp_host: '$vm'
cdn_host: '$vm'
images_host: '$vm'
ansible_host: '$vm'
jump_host: '$vm'
jenkins_host: '$vm'
keys_host: '$vm'
keys_port: '80'
keys_path: '/authorized_keys'
use_local_keys: '~/.ssh/authorized_keys'
