vm_memory = 8192
vm_cpus   = 4

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.hostname = 'iso-builder'

  ["vmware_workstation", "vmware_fusion"].each do |vmware_provider|
    config.vm.provider(vmware_provider) do |vmware|
      vmware.whitelist_verified = true
      vmware.gui = true
      vmware.vmx["memsize"] = vm_memory
      vmware.vmx["numvcpus"] = vm_cpus
      vmware.vmx["vhv.enable"] = "TRUE"
    end
  end

  config.vm.provider :virtualbox do |vb|
    vb.memory = vm_memory
    vb.cpus = vm_cpus
  end

  config.vm.provider :libvirt do |libvirt|
    # libvirt.random_hostname = true
    # this should be kvm for 5x more performance but having problems
    # libvirt.driver = 'qemu'

    # add more juice otherwise we only get 1 cpu and 512m
    libvirt.cpus = vm_cpus
    libvirt.memory = vm_memory
    libvirt.nested = 'true'
  end

  config.vm.synced_folder './', '/vagrant'

  config.vm.provision 'shell', 
    env: {
      "ACNG_HOST" => ENV['ACNG_HOST'],
      "ACNG_PORT" => ENV['ACNG_PORT'],
      "APPROX_HOST" => ENV['APPROX_HOST'],
      "APPROX_PORT" => ENV['APPROX_PORT']
      }, inline: <<-SHELL
    
    ACNG_URL="http://$ACNG_HOST:$ACNG_PORT"
    APPROX_URL="http://$APPROX_HOST:$APPROX_PORT/debian/"
    echo 'Using '$ACNG_URL' and '$APPROX_URL' for deb pkg caching'
    echo 'Acquire::http::Proxy "'$ACNG_URL'";' > /etc/apt/apt.conf.d/02proxy

cat > /etc/environment <<-EOF
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="C"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
EOF

    . /etc/environment
    cat /etc/locale.gen | sed 's/^# en_US.UTF-8/en_US.UTF-8/g' > /etc/locale.gen.new
    rm /etc/locale.gen
    mv /etc/locale.gen.new /etc/locale.gen
    locale-gen en_US.UTF-8
    dpkg-reconfigure -f noninteractive locales
    apt-get -y update
    apt-get -y install simple-cdd debhelper devscripts
    apt-get -y install qemu-kvm libvirt-daemon-system bridge-utils
    cd /vagrant

    if [ -f /vagrant/tmp/mirror/db/lockfile ]; then
      rm /vagrant/tmp/mirror/db/lockfile
    fi 

    # Need to cycle here over all the profiles to build CDs for
    CMD='echo build-simple-cdd --debian-mirror '$APPROX_URL
    sudo su -c '$1' vagrant -- $CMD
  SHELL
end
