#!/bin/sh

BASE_DIR="`dirname \"$0\"`"
BASE_DIR="`( cd \"$BASE_DIR\" && pwd )`"
TOP_DIR="$BASE_DIR/.."

#
# Functions
#

trim () {
    echo "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

echo_err () {
   echo "[ERROR] $@" >&2
}

# ARGS: $1 - normalize size values into megabytes 3 TB, 3000GB, 23949583M etc
# OUTPUTS: amount in megabytes as a numeric string
in_mb () {
    # values from parted are in GB so let us confirm
    if [ -z "echo $1 | grep GB" ]; then
        echo_err "Failed to detect units in input size: $1"
        exit 1
    fi

    gb=`echo $1 | sed -e 's/GB//'`
    echo $(($gb * 1000))
}

