#!/bin/bash

function stretch_preseed_usage() {
  echo 'Generates a Debian Stretch preseed using the environment and machine definitions.'
  echo 'stretch-preseed <environment> <machine>'
}

function usage() {
  local script="$(basename $0)"
  case "$script" in 
    "stretch-preseed.sh")
      stretch_preseed_usage
      ;;
    *)
      echo "Don't know what to do \$script = $script"
      ;;
  esac
}

BASE_DIR="`dirname \"$0\"`"
BASE_DIR="`( cd \"$BASE_DIR\" && pwd )`"
TOP_DIR="$BASE_DIR/.."

. $TOP_DIR/lib/general
. $TOP_DIR/lib/yaml
. $TOP_DIR/lib/settings
. $TOP_DIR/lib/load_env "$1"

if [ ! -f "$env_conf" ]; then
  . $TOP_DIR/bin/environment.sh $env_name
fi

mach_def="$2"
mach_def_path="$env_dir/$mach_def"

# TODO: Add ability to launch multiple VM's at one time.

if [ -n "$mach_def" -a -d "$mach_def_path" ]; then
  nics_dbf="$mach_def_path/nics.yml"
  if [ ! -f $nics_dbf ]; then
    err "Network card db file $nics_dbf does not exist for $mach_def"
    usage; exit 12
  fi

  mach_dbf="$mach_def_path/machine.yml"
  if [ ! -f "$mach_dbf" ]; then
    err "Machine db file $mach_dbf does not exist for $mach_def"
    usage; exit 13
  fi

  drives_dbf="$mach_def_path/drives.yml"
  if [ ! -f "$drives_dbf" ]; then
    err "Drive db file $drives_dbf does not exist for $mach_def"
    usage; exit 14
  fi
else
    err "The machine directory for $mach_def does not exist"
    err "Tried the following path:"
    err "    -> $mach_def_path"
    usage; exit 1
fi

