#!/bin/bash


BASE_DIR="`dirname \"$0\"`"
BASE_DIR="`( cd \"$BASE_DIR\" && pwd )`"
TOP_DIR="$BASE_DIR/.."

. $TOP_DIR/lib/general
. $TOP_DIR/lib/yaml
. $TOP_DIR/lib/settings

env_name="$1"
env_dir="$environments/$env_name"
env_conf_file="$environments/$env_name/environment"

mach_def="$2"
mach_def_path="$environments/$env_name/$mach_def"

if [ -n "$env_name" ]; then
  if [ ! -d "$env_dir" ]; then
    echo_err "Environment directory $env_dir for $envconf does not exist"
    usage_info; exit 20
  elif [ ! -f "$env_conf_file" ]; then
    echo_err "No environment configuration file was found for $env_name"
    usage_info; exit 21
  fi

  . "$env_conf_file"
else
  echo_err "No valid environment name was provided."
  usage_info; exit 2
fi

# TODO: Add ability to launch multiple VM's at one time.

if [ -n "$mach_def" -a -d "$mach_def_path" ]; then
  nics_dbf="$mach_def_path/nics.yml"
  if [ ! -f $nics_dbf ]; then
    echo_err "Network card db file $nics_dbf does not exist for $mach_def"
    usage_info; exit 12
  fi

  mach_dbf="$mach_def_path/machine.yml"
  if [ ! -f "$mach_dbf" ]; then
    echo_err "Machine db file $mach_dbf does not exist for $mach_def"
    usage_info; exit 13
  fi

  drives_dbf="$mach_def_path/drives.yml"
  if [ ! -f "$drives_dbf" ]; then
    echo_err "Drive db file $drives_dbf does not exist for $mach_def"
    usage_info; exit 14
  fi
else
    echo_err "The machine directory for $mach_def does not exist"
    echo_err "Tried the following path:"
    echo_err "    -> $mach_def_path"
    usage_info; exit 1
fi

