#!/bin/bash

BASE_DIR="`dirname \"$0\"`"
BASE_DIR="`( cd \"$BASE_DIR\" && pwd )`"
TOP_DIR="$BASE_DIR/.."

. $TOP_DIR/lib/general
. $TOP_DIR/lib/yaml
. $TOP_DIR/lib/settings

env_name="$1"
env_dir="$TOP_DIR/$environments/$env_name"
env_conf_file="$env_dir/environment"

if [ -f "$env_conf_file" ]; then
  . $TOP_DIR/bin/environment.sh $env_name
fi

mach_def="$2"
mach_def_path="$env_dir/$mach_def"

if [ -n "$env_name" ]; then
  if [ ! -d "$env_dir" ]; then
    err "Environment directory $env_dir for $envconf does not exist"
    usage_info; exit 20
  elif [ ! -f "$env_conf_file" ]; then
    err "No environment configuration file was found for $env_name"
    usage_info; exit 21
  fi

  . "$env_conf_file"
else
  err "No valid environment name was provided."
  usage_info; exit 2
fi

# TODO: Add ability to launch multiple VM's at one time.

if [ -n "$mach_def" -a -d "$mach_def_path" ]; then
  nics_dbf="$mach_def_path/nics.yml"
  if [ ! -f $nics_dbf ]; then
    err "Network card db file $nics_dbf does not exist for $mach_def"
    usage_info; exit 12
  fi

  mach_dbf="$mach_def_path/machine.yml"
  if [ ! -f "$mach_dbf" ]; then
    err "Machine db file $mach_dbf does not exist for $mach_def"
    usage_info; exit 13
  fi

  drives_dbf="$mach_def_path/drives.yml"
  if [ ! -f "$drives_dbf" ]; then
    err "Drive db file $drives_dbf does not exist for $mach_def"
    usage_info; exit 14
  fi
else
    err "The machine directory for $mach_def does not exist"
    err "Tried the following path:"
    err "    -> $mach_def_path"
    usage_info; exit 1
fi

