#!/bin/bash

BASE_DIR="`dirname \"$0\"`"
BASE_DIR="`( cd \"$BASE_DIR\" && pwd )`"
TOP_DIR="$BASE_DIR/.."

. $TOP_DIR/lib/general
. $TOP_DIR/lib/yaml

# Pulls in environments var which we need
rec 0 $TOP_DIR/settings.yml
overrides="$(eval echo $overrides)"
if [ -f "$overrides/settings.yml" ]; then
  rec 0 "$overrides/settings.yml"
fi

if [ "$USER" == "vagrant" -a "$(hostname)" == "iso-builder" ]; then
  environments='/var/www/html/environments'
else
  environments="$(eval echo $environments)"
fi
